import { StyleSheet, Platform } from 'react-native';
import Colors from './colors';

export const commonStyles = StyleSheet.create({
  flex1: { flex: 1 },
  container: { flex: 1, backgroundColor: Colors.background },
  centerSafe: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: Colors.background },
  headerSafe: { backgroundColor: Colors.surface },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingVertical: 12 },
  headerRTL: { flexDirection: 'row-reverse' },
  headerTitle: { fontSize: 18, fontWeight: '700' as const, color: Colors.text },
  pageTitle: { fontSize: 24, fontWeight: '800' as const, color: Colors.text, marginTop: 8 },
  backBtn: { width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center' },
  card: {
    backgroundColor: Colors.surface,
    borderRadius: 20,
    padding: 20,
    margin: 20,
    shadowColor: Colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: Colors.shadow.opacity,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionCard: {
    backgroundColor: Colors.surface,
    borderRadius: 20,
    padding: 20,
    marginHorizontal: 20,
    marginBottom: 16,
    shadowColor: Colors.shadow.color,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: Colors.shadow.opacity,
    shadowRadius: 8,
    elevation: 3,
  },
  cardRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 6 },
  rowRTL: { flexDirection: 'row-reverse' },
  label: { fontSize: 14, color: Colors.textSecondary, fontWeight: '500' as const },
  divider: { height: 1, backgroundColor: Colors.divider, marginVertical: 12 },
  rtlText: { textAlign: 'right', writingDirection: 'rtl' },
  inputRTL: { writingDirection: 'rtl' },
  btnPressed: { opacity: 0.9 },
  btnDisabled: { opacity: 0.5 },
  bottomSpacer: { height: 30 },
  orderNumber: {
    fontSize: 14,
    fontWeight: '700' as const,
    color: Colors.primary,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
  },
  sectionTitle: { fontSize: 16, fontWeight: '700' as const, color: Colors.text, marginBottom: 14 },
  dishTitle: { fontSize: 22, fontWeight: '800' as const, color: Colors.text },
  priceValue: { fontSize: 16, fontWeight: '700' as const, color: Colors.text },
  totalLabel: { fontSize: 15, fontWeight: '700' as const, color: Colors.text },
  totalValue: { fontSize: 18, fontWeight: '800' as const, color: Colors.primary },
  dateValue: { fontSize: 13, color: Colors.textTertiary },
  noteText: { fontSize: 14, color: Colors.text, lineHeight: 20, marginTop: 6 },
  paymentBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, gap: 5 },
  paymentBadgeText: { fontSize: 12, fontWeight: '600' as const },
  statusBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 12, gap: 5 },
  statusBadgeText: { fontSize: 12, fontWeight: '600' as const },
  primaryBtn: { backgroundColor: Colors.primary, height: 48, borderRadius: 14, justifyContent: 'center', alignItems: 'center' },
  primaryBtnText: { color: Colors.white, fontSize: 16, fontWeight: '700' as const },
  actionBtnRow: { flexDirection: 'row', height: 54, borderRadius: 16, justifyContent: 'center', alignItems: 'center', gap: 10, marginHorizontal: 20, marginBottom: 16 },
  actionBtnText: { color: Colors.white, fontSize: 17, fontWeight: '700' as const },
  formInput: {
    backgroundColor: Colors.background,
    borderRadius: 12,
    padding: 14,
    fontSize: 14,
    color: Colors.text,
    borderWidth: 1,
    borderColor: Colors.borderLight,
    marginBottom: 4,
  },
  formLabel: { fontSize: 13, fontWeight: '600' as const, color: Colors.textSecondary, marginBottom: 6, marginTop: 8 },
  driverRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  driverIconWrap: { width: 48, height: 48, borderRadius: 24, backgroundColor: Colors.primaryFaded, justifyContent: 'center', alignItems: 'center' },
  menuSection: { backgroundColor: Colors.surface, borderRadius: 16, marginHorizontal: 20, marginBottom: 16, overflow: 'hidden' as const },
  menuRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, paddingVertical: 16, gap: 14, borderBottomWidth: 1, borderBottomColor: Colors.divider },
  menuText: { fontSize: 15, color: Colors.text, flex: 1 },
  menuValue: { fontSize: 14, color: Colors.textTertiary },
  infoRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 18, paddingVertical: 14, gap: 14, borderBottomWidth: 1, borderBottomColor: Colors.divider },
  infoText: { fontSize: 15, color: Colors.text, flex: 1 },
  logoutBtn: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10, marginHorizontal: 20, marginTop: 8, paddingVertical: 16, backgroundColor: Colors.errorLight, borderRadius: 16 },
  logoutText: { fontSize: 16, fontWeight: '700' as const, color: Colors.error },
  versionText: { fontSize: 12, color: Colors.textTertiary, textAlign: 'center', marginTop: 20 },
});
